@startuml analyzer_flow
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Verdana"
skinparam defaultFontSize 12

title Алгоритм обработки события

start

:Получение сообщения из очереди;
note right: Содержит ссылку на статью\nи ID события GDELT

:Извлечение текста статьи;
if (Текст доступен?) then (да)
  :Сортировка упоминаний по дате;
  :Реферирование описания события;
  :Классификация события;
  note left: Определение категории угрозы\nи уровня критичности
  
  :Геопарсинг;
  :Генерация описания события;
  
  :Отправка результата на серверную часть приложения;
else (нет)
  :Логирование ошибки;
  :Пропуск обработки;
endif

stop
@enduml
