@startuml components_diagramm
top to bottom direction
skinparam defaultTextAlignment center
skinparam componentStyle uml2

' Настройки для экономной печати
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Verdana"
skinparam defaultFontSize 12

' Принудительный белый фон для всех типов элементов на этой диаграмме
skinparam ComponentBackgroundColor white
skinparam DatabaseBackgroundColor white
skinparam QueueBackgroundColor white

skinparam ComponentBorderColor black
skinparam DatabaseBorderColor black
skinparam QueueBorderColor black

' Увеличиваем расстояния, чтобы разгрузить перекрестные связи
skinparam nodesep 60
skinparam ranksep 80

' Источники и сбор (Верхний уровень)
[Источник событий] as GDELT
[Модуль сбора данных] as Fetcher

' Очередь и логика (Средний уровень)
queue "Очередь сообщений" as RMQ
[Модуль анализа] as Analyzer
[Локальная LLM] as Ollama
[Локальная модель перевода] as Translator

' Хранение и UI (Нижний уровень)
[Серверная часть приложения] as Core
database "База данных" as CDB
[Пользовательский интерфейс] as Web

' --- СВЯЗИ ---

' 1. Сбор данных
GDELT --> Fetcher : CSV-архивы
Fetcher --> RMQ : Данные событий

' 2. Анализ данных
RMQ --> Analyzer : Получение данных
Analyzer --> Translator : Перевод полей
Analyzer -right-> Ollama : Генерация текста
Analyzer --> Core : Обработанные события

' 3. Хранение и отображение
Core --> CDB : Постоянное хранение
Web --> Core : REST API / Карта

@enduml