@startuml components_diagramm
top to bottom direction
skinparam defaultTextAlignment center
skinparam componentStyle uml2

' Источники и сбор (Верхний уровень)
[Источник событий] as GDELT
[Модуль сбора данных] as Fetcher
database "Промежуточная БД" as SDB

' Очередь и логика (Средний уровень)
queue "Очередь сообщений" as RMQ
[Модуль анализа] as Analyzer
[Локальная LLM] as Ollama

' Хранение и UI (Нижний уровень)
[Серверная часть приложения] as Core
database "Основная БД" as CDB
[Пользовательский интерфейс] as Web

' --- СВЯЗИ ---

' 1. Сбор данных
GDELT --> Fetcher : CSV-архивы
Fetcher --> SDB : Сохранение данных
Fetcher --> RMQ : ID событий

' 2. Анализ данных
RMQ --> Analyzer : Получение ID
Analyzer -left-> SDB : Чтение данных
Analyzer -right-> Ollama : Генерация сводки
Analyzer --> Core : Обработанные события

' 3. Хранение и отображение
Core --> CDB : Постоянное хранение
Web --> Core : REST API / Карта

@enduml