@startuml deployment_diagramm
left to right direction

skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Verdana"
skinparam defaultFontSize 24
skinparam nodesep 100

' Принудительный белый фон
skinparam NodeBackgroundColor white
skinparam ComponentBackgroundColor white
skinparam DatabaseBackgroundColor white
skinparam CloudBackgroundColor white

skinparam NodeBorderColor black
skinparam ComponentBorderColor black
skinparam DatabaseBorderColor black
skinparam CloudBorderColor black

' === ВНЕШНИЕ УЗЛЫ И КЛИЕНТЫ ===

node "User Device" {
    component [Browser] as Browser
}

cloud "External Sources" {
    [GDELT Project] as GDELT
    [News Media / APIs] as News
}

' === ТВОЯ СЕРВЕРНАЯ ИНФРАСТРУКТУРА (РАЗДЕЛЬНЫЕ СЕРВЕРЫ) ===

node "Web Server" {
    component [Nginx] as Nginx
}

node "Analytics Server" {
    component [Fetcher] as Fetcher
    component [Analyzer] as Analyzer
}

node "Ollama Server" {
    component [Ollama (Local LLM)] as Ollama
}

node "Backend Server" {
    component [Backend] as Backend
}

node "Message Broker Server" {
    component [RabbitMQ] as RMQ
}

node "Database Server" {
    database "PostgreSQL + PostGIS" as DB
}


Browser --> Nginx : HTTP / HTTPS
GDELT --> Fetcher : HTTP / FTP
News --> Fetcher : HTTP API

Nginx ---> Backend : HTTP
Analyzer --> Ollama : HTTP

Fetcher ---> RMQ : AMQP
Analyzer ---> RMQ : AMQP
Analyzer ---> Backend : HTTP

Backend ---> DB : TCP

@enduml