@startuml seq_diagramm
' Автоматическая нумерация шагов для удобства описания в отчете
autonumber
' Ограничение ширины текста над стрелками, чтобы текст не был в одну длинную строку
skinparam maxMessageSize 200

' --- Настройки для экономной печати ---
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Verdana"
skinparam defaultFontSize 20

' Принудительный белый фон для всех элементов
skinparam ParticipantBackgroundColor white
skinparam DatabaseBackgroundColor white
skinparam QueueBackgroundColor white
skinparam ActorBackgroundColor white

skinparam ParticipantBorderColor black
skinparam DatabaseBorderColor black
skinparam QueueBorderColor black
skinparam ActorBorderColor black

' Убираем серый фон у разделителей групп (== Сбор данных ==)
skinparam SequenceDividerBackgroundColor white
skinparam SequenceDividerBorderColor black

' --- Растягивание по горизонтали ---
' Увеличиваем отступы между всеми колонками (участниками)
skinparam ParticipantPadding 80

participant "GDELT" as G
participant "Модуль сбора\nданных" as F
queue "RabbitMQ" as RMQ
participant "Модуль\nанализа" as A
participant "Серверная часть\nприложения" as C
database "PostgreSQL\n" as CDB
actor "Пользователь\n" as U

== Сбор данных ==
G -> F : CSV-архив GDELT
F -> RMQ : Публикация пакета\nданных событий

== Анализ данных ==
RMQ -> A : Получение пакета\nданных событий
A -> A : Классификация
A -> A : Геопарсинг
A -> A : Генерация описания
A -> C : POST /api/v1/internal/events\n(Передача обработанных данных)
C -> CDB : Сохранение обработанного\nсобытия

== Уведомление пользователей ==
C -> CDB : Поиск пользователей\nпоблизости и на маршруте
C -> U : Отправка Push-уведомления
U -> C : GET /api/v1/events
C -> U : Возврат списка событий\nв формате GeoJSON

@enduml