@startuml use_case_diagramm
left to right direction

' Настройки для экономной печати
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Verdana"
skinparam defaultFontSize 12

' Принудительный белый фон
skinparam UsecaseBackgroundColor white
skinparam ActorBackgroundColor white
skinparam RectangleBackgroundColor white

skinparam UsecaseBorderColor black
skinparam ActorBorderColor black
skinparam RectangleBorderColor black

' Увеличиваем отступы для чистоты схемы
skinparam nodesep 40
skinparam ranksep 70

' Определяем акторов
actor "Путешественник" as User
actor "Менеджер по рискам" as TRM

rectangle "Система мониторинга рисков Horizon" {
    
    ' Общие функции
    usecase "Регистрация / Авторизация" as UC_Auth
    usecase "Просмотр карты рисков" as UC_Map
    usecase "Получение уведомлений\nо безопасности" as UC_Notify
    usecase "Получение email-\nуведомлений" as UC_Email
    usecase "Фильтрация событий\n(по типу, дате, угрозе)" as UC_Filter

    ' Функции путешественника
    usecase "Настройка личного\nмаршрута поездки" as UC_Route

    ' Функции риск-менеджера
    usecase "Отслеживание геопозиции\nтуристов / сотрудников" as UC_TrackUsers
    usecase "Глобальный мониторинг\nинцидентов" as UC_GlobalEvents
    usecase "Анализ зон пересечения\nмаршрутов с рисками" as UC_AnalyzeRoutes

}

' === СВЯЗИ АКТОРОВ (СЛЕВА) ===
User --> UC_Route
User --> UC_Auth
User --> UC_Map
User --> UC_Notify

TRM --> UC_Auth
TRM --> UC_Map
TRM --> UC_Notify
TRM --> UC_TrackUsers
TRM --> UC_GlobalEvents
TRM --> UC_AnalyzeRoutes

' === СВЯЗИ АДМИНА (СПРАВА) ===
' Размещаем админа справа, чтобы его стрелки не пересекались с пользовательскими

' === ЗАВИСИМОСТИ (EXTEND) ===
UC_Notify <.. UC_Email : <<extend>>
UC_Map <.. UC_Filter : <<extend>>
UC_GlobalEvents <.. UC_Filter : <<extend>>

@enduml